### PR TITLE
Add support for credentials plugin for deploy key

### PR DESCRIPTION
**Pull request by nfalco79**
Here should be add the warning message to advise user that persistence is not compatible.

image

I had try to make this back compatible but the problem is how the build step is build.

### CODE REVIEW

**Comment by ctron** [comment]
Big thanks for this change!

I would only like to understand what will happen to existing users when they do upgrade this plugin.

**Comment by nfalco79** [comment]
When manage jenkins in plugin section they got a red [warning message](https://wiki.jenkins.io/display/JENKINS/Marking+a+new+plugin+version+as+incompatible+with+older+versions).

Jobs must be re-configured selecting the credentials.

**Review by ctron — APPROVED** [review]
LGTM

**Comment by nfalco79** [comment]
Add half back compatible mode.
This means that it can run old job configuration with deployKey in plain text but if you edit the job configuration for some reason you have to setup deploy key with new credentials.

This allow update the plugin to new one and run without fix each job.

**Comment by ctron** [comment]
Just let me know when you want me to release the next version!

Many thanks for your help!

**Comment by nfalco79** [comment]
ready for a new release

**Pull request merged**
