### PR TITLE
Fix upload from Jenkins-Slaves

### PR DESCRIPTION
**Pull request by chrismathis**
Make UploadFiles and DroneRecorder Serializable to be able to run on a Jenkins slave. 
Fixes Issue #7 and #11.

I've tested this on our Freestyle and Pipeline Jobs on Jenkins-Master and Slave - with the V3 API.
What does not seem to work yet is the cool V3-result-widget from slaves.

There is some potential for further refactoring so that DroneRecorder itself does not need to be Serializeable.

### CODE REVIEW

**Comment by ctron** [comment]
Look good to me. Could you simply format this with spaces instead of tabs?

Will this still work with Jenkins 1.x?

**Comment by chrismathis** [comment]
Changed to spaces.

I did not change anything Jenkins API wise. So if it worked with 1.x before it should still work.
I don't think adding the Serializable on DroneRecorder can be an issue.

**Comment by ctron** [comment]
So if I make an new version, could you test it?

**Comment by chrismathis** [comment]
Yes I can.

**Comment by ctron** [comment]
https://web.tresorit.com/l#MQribdmvVok7eLOz2U3r8g

This will expire in 30 days.

**Comment by chrismathis** [comment]
Works for me.
Tested on master and slave with V2, V3, Pipeline and Freestyle Jobs.

**Comment by ctron** [comment]
Ok, this should be released. It may take a while into this pops up in the update center of Jenkins.

Please close this issue once you can confirm this.

Many thanks!!

**Pull request merged**
